import React from 'react';
import { Container } from 'react-bootstrap';

export default function About() {
  return (
    <section id="about" className='pt-5'>
      <Container>
        <h2>About Us</h2>
        <p className='text-lowercase'>
          WE, QUALITY LEATHER, ARE A SPECIALISED LEATHER PRODUCTS MANUFACTURING
          AND EXPORTING COMPANY ASSURING POSSIBLE FINEST QUALITY AT CONSIDERABLY
          COMPETITIVE PRICE. WE ARE PRIVILIDGED FOR PROVIDING THE BEST OF OUR
          SERVICES FOR BOTH KIND OF CLIENTS EXPECTING LUXURIOUS QUALITY PRODUCTS
          FOR BRANDS OR MANAGING VAST SUPPLY CHAINS KEEPING PRICE COMPETITIVE
          CONSIDERING END USERS' AFFORDANCE.HAVING REGISTRATION FOR BUSINESSES
          IN EUROPEAN UNION TROUGH REX REGISTRATION, WE GRAB OPPURTUNITIES OF
          PROVIDING OUR PRODUCTS FOR EUROPEAN CLIENTS AS WELL ALONGWITH REST OF
          THE WORLD.
        </p>
      </Container>
    </section>
  );
}
